send_message:
  name: Envoyer un message
  description: Envoie un message au Smart Led Messenger
  fields:
    message:
      required: true
      selector:
        text:
    intensity:
      required: false
      default: 5
      selector:
        number:
          min: 0
          max: 15
          mode: slider
    speed:
      required: false
      default: 20
      selector:
        number:
          min: 10
          max: 50
          mode: slider
