send:
  name: Envoyer un message
  description: Envoie un message au Smart Led Messenger
  fields:
    message:
      name: Message
      description: Texte à afficher
      required: true
      selector:
        text:
    intensity:
      name: Intensité
      description: 0 à 15
      required: false
      selector:
        number:
          min: 0
          max: 15
    speed:
      name: Vitesse
      description: 10 à 50
      required: false
      selector:
        number:
          min: 10
          max: 50
